server.port=8080
server.forward-headers-strategy=FRAMEWORK
spring.profiles.default=prod

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.liquibase.enabled=false

app.speech-to-text.type=lemonfox-api
