version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend-app:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # React development server port
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # For hot-reloading in Docker
    depends_on:
      - backend-app # Frontend depends on backend for API calls

  backend-app:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend-app:/app
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
